# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
# production:
#   adapter: redis
#   url: redis://localhost:6379/1

# development:
#   adapter: async

# test:
#   adapter: async
  development: &development  
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true
  test: *development  

  production: &production  
  :url: redis://redistogo:694de15c3ee7ffd8563d7f68d5fbd213@hoki.redistogo.com:9958/
  :host: hoki.redistogo.com
  :port: 9958
  :password: 694de15c3ee7ffd8563d7f68d5fbd21
  :inline: true
  :timeout: 1
  
